apiVersion: apps/v1
kind: Deployment
metadata:
  name: zhong-discord-bot
  labels:
    app: bot
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  selector:
    matchLabels:
      app: bot
  template:
    metadata:
      labels:
        app: bot
    spec:
      containers:
      - name: bot
        image: asia.gcr.io/zhong-discord-bot/discord-bot:latest
        env:
          - name: BOT_TOKEN
            valueFrom:
              secretKeyRef:
                name: bot-secert
                key: BOT_TOKEN
